### ISSUE TITLE
Improve error message when the `git add` command failed

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/gulp-gitstage#5]
When the `git add [FILE]` command fails it currently outputs a generic message (`"git add failed."`), but I have no idea why the command would fail and what the error would be. I'm talking about [this line of code](https://github.com/ericcornelissen/gulp-gitstage/blob/afb822de7a1ae32ef305bb59513b1b6219f2120a/index.js#L16).

**Comment by ericcornelissen** [comment]
One possible error is due to multiple git instances trying to add files simultaneously ⬇️ Progress being tracked in #14

```
{
  Error: Command failed: git add [FILE]
  fatal: Unable to create '.../.git/index.lock': File exists.

    Another git process seems to be running in this repository, e.g.
    an editor opened by 'git commit'. Please make sure all processes
    are terminated then try again. If it still fails, a git process
    may have crashed in this repository earlier:
    remove the file manually to continue.

  killed: false,
  code: 128,
  signal: null,
  cmd: 'git add [FILE]'
}
```

**Comment by ericcornelissen** [comment]
Another possible error is when the file to add was not found in the repository ⬇️

```
{
  Error: Command failed: git add [FILE]
  fatal: pathspec '[FILE]' did not match any files

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

  killed: false,
  code: 128,
  signal: null,
  cmd: 'git add [FILE]'
}
```
